### PR TITLE
Cricket Implem + few things

### PR DESCRIPTION
**Pull request by ggerbaud**
- Cricket game implem (regular, cut-throat, no-score)
- refactoring in games
- bug fix

### CODE REVIEW

**Comment by mathieu-pousse** [comment]
LGTM ping @erwannT

**Comment by mathieu-pousse** [comment]
c'est nouveau ?  on merge avec un sel LGTM ?

**Comment by erwannT** [comment]
LGTM !!!

**Comment by ggerbaud** [comment]
LGTMT

**Pull request merged**
